services:
  engine:
    container_name: traversal-engine
    build: .
    command: ['php', '-S', "0.0.0.0:8080", "/app/public/server.php"]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./output:/app/output
      - ./tmp:/app/tmp
    env_file:
      - .env
    environment:
      - XDEBUG_MODE=coverage,debug
      - TZ=Asia/Jakarta
    networks:
      - traversal

networks:
  traversal:

volumes:
  logs: