services:
  engine:
    container_name: traversal-engine
    build: ./app-engine
    command: ['php', '-S', "0.0.0.0:8080", "/app/public/server.php"]
    ports:
      - "8080:8080"
    volumes:
      - ./app-engine/src:/app/src
      - ./app-engine/bin:/app/bin
      - ./app-engine/public:/app/public
      - ./tmp:/app/tmp
      - ./reports/engine:/app/reports
    env_file:
      - ./app-engine/.env
    networks:
      - traversal

  socketio:
    container_name: traversal-socketio
    build: ./app-server
    volumes:
      - ./app-server/src:/app/src
      - ./logs/server:/app/logs
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=development
    depends_on:
      - engine
    networks:
      - traversal

networks:
  traversal:

volumes:
  logs: