services:
  engine:
    container_name: traversal-engine
    build: .
    volumes:
      - ./src:/app/src
      - ./materials:/app/materials
      - ./logs:/app/workspace/reports
      - ./vendor:/app/vendor
      - ./composer.json:/app/composer.json
