services:
  engine:
    container_name: traversal-engine
    build: .
    command: ['php', '-S', "0.0.0.0:8080", "/app/main_server.php"]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./outputs:/app/outputs
      - ./tmp:/tmp
    env_file:
      - .env
    environment:
      - XDEBUG_MODE=coverage,debug
      - TZ=Asia/Jakarta
    networks:
      - traversal

networks:
  traversal:

volumes:
  logs: