services:
  engine:
    container_name: traversal-engine
    build: ./app-engine
    command: ['php', 'run.php']
    volumes:
      - ./app-engine/src:/app
      - ./app-engine/vendor:/app/vendor
      - ./logs:/app/workspace/reports
    environment:
      - APP_ENV=development
    networks:
      - traversal

  socketio:
    container_name: traversal-socketio
    build: ./app-server
    volumes:
      - ./app-server:/app
      - ./app-server/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=development
    depends_on:
      - engine
    networks:
      - traversal

networks:
  traversal:

volumes:
  logs: