services:
  engine:
    container_name: traversal-engine
    build: ./app-engine
    command: ['php', '-S', "0.0.0.0:8080", "server.php"]
    ports:
      - "8080:8080"
    volumes:
      - ./app-engine/src:/app/src
      - ./workspace:/app/workspace/reports
    environment:
      - APP_ENV=development
    networks:
      - traversal

  socketio:
    container_name: traversal-socketio
    build: ./app-server
    volumes:
      - ./app-server/src:/app/src
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=development
    depends_on:
      - engine
    networks:
      - traversal

networks:
  traversal:

volumes:
  logs: