services:
  engine:
    container_name: traversal-engine
    build: ./engine
    command: ['php', '-S', "0.0.0.0:8080", "/app/public/server.php"]
    ports:
      - "8080:8080"
    volumes:
      - ./engine:/app
      - ./reports/engine:/app/reports
      - ./tmp:/app/tmp
    env_file:
      - .env
    environment:
      - APP_ENV_LOADER=docker-compose
      - TZ=Asia/Jakarta
      - APP_ENV=development
      - APP_DEBUG=true
      - XDEBUG_MODE=coverage,debug
      - SOCKET_HOST=socket
      - SOCKET_PORT=3000
    networks:
      - traversal

  socket:
    container_name: traversal-socket
    build: ./socket
    volumes:
      - ./socket:/app
      - ./reports/socket:/app/logs
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=development
      - TZ=Asia/Jakarta
    depends_on:
      - engine
    networks:
      - traversal

networks:
  traversal:

volumes:
  logs: